name: CI

on: [push]

jobs:
  lint:
    env:
      GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      _authToken: ${{secrets.GITHUB_TOKEN}}
      NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: 13
          registry-url: https://npm.pkg.github.com/
          scope: '@alanramsay'
      - name: npm install and Lint
        run: |
          cat .npmrc
          npm ci --verbose
          npm run lint
