name: CI

on: [push]

jobs:
  lint:
    env:	
      GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: npm install and Lint
        run: |
          npm ci
          npm run lint
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
